# Generated by Django 6.1 on 2026-08-28 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction', models.JSONField(blank=True, default=dict)),
                ('uncertainty', models.JSONField(blank=True, default=dict)),
                ('priority', models.JSONField(blank=True, default=dict)),
                ('duplicate', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(default='mock', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('is_available', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='emergencies.emergencyreport')),
            ],
            options={
                'verbose_name': 'Agent analysis',
                'verbose_name_plural': 'Agent analyses',
            },
        ),
    ]
