# Generated by Django 6.1 on 2026-08-29 19:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RelayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_node', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('hop_count', models.PositiveIntegerField(default=0)),
                ('max_hops', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_status', models.CharField(choices=[('QUEUED', 'Queued (outbox)'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered to backend')], default='QUEUED', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('synced_to_server', models.BooleanField(default=False)),
                ('carried_by', models.ManyToManyField(blank=True, related_name='carried_messages', to='relay.relaydevice')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relay_messages', to='emergencies.emergencyreport')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
