# Generated by Django 6.1 on 2026-08-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('BUILDING_COLLAPSE', 'Building Collapse'), ('MEDICAL', 'Medical'), ('FIRE', 'Fire'), ('FLOOD', 'Flood'), ('LANDSLIDE', 'Landslide'), ('TRAPPED', 'Trapped'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_accuracy', models.FloatField(blank=True, null=True)),
                ('people_affected', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWING', 'Reviewing'), ('VERIFIED', 'Verified'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('priority', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='UNASSIGNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
